### PR TITLE
Add getter and comparison to NSDate

### PR DESCRIPTION
**Pull request by PGLongo**
Hi,

I have added getters to NSDate. Now you can do:

```swift
let date = NSDate()
let year = date.year
```
instead of 

```swift
let date = NSDate()
let calendar = NSCalendar.currentCalendar()
let components = calendar.components(.CalendarUnitYear, fromDate: date)
let year = components.year
```

I have also added Comparison operator: <, <=, >, >=, == and updated the docs and README.md

### CODE REVIEW

**Comment by pNre** [comment]
Before merging, there's a bug in the `>` operator implementation you should fix.
```
public func >(lhs: NSDate, rhs: NSDate) -> Bool {
    return !(lhs < rhs)
}
```
If `lhs == rhs` the function returns `true`.

**Comment by PGLongo** [comment]
Thanks!

Fixed replacing 

```swift
public func >(lhs: NSDate, rhs: NSDate) -> Bool {
    return !(lhs < rhs)
}
```
with

```swift
public func >(lhs: NSDate, rhs: NSDate) -> Bool {
    return !(lhs <= rhs)
}
```

I have also updated the test

**Comment by michaeleisel** [comment]
You should only implement == and > (or maybe <, I forget, but just one of the two). Swift infers the other variants, e.g. >=, for you.

**Comment by michaeleisel** [comment]
@PGLongo @pNre

**Pull request merged**
