### PR TITLE
Transpose

### PR DESCRIPTION
**Pull request by michaeleisel**
This needs to be turned into a method that transposes the array it's called on, but I can't figure out how to enforce that the array be composed of arrays, similar to how we enforce that an array be composed of Equatables when we call unique() on it. Any ideas?

### CODE REVIEW

**Comment by michaeleisel** [comment]
Why were so many of my PRs closed without merging?

**Comment by michaeleisel** [comment]
@pNre

**Comment by pNre** [comment]
Well, there was a problem on one of them (combinations), I even opened a pull request on your branch but since you stopped answering I figured you lost interest.
Anyway if you're back on the code I can reopen them.

**Comment by michaeleisel** [comment]
@pNre what was the problem with the combinations branch? There was a problem with the permutations branch, although that's addressed in a new PR.

**Comment by pNre** [comment]
There isn't as I wrote I'm more than happy to merge everything. I just didn't want half of the features, combinations without permutations.

**Comment by michaeleisel** [comment]
OK, great. Anything you need from me before you merge all of these branches?

**Comment by pNre** [comment]
Just a confirmation, is that all?
* https://github.com/pNre/ExSwift/pull/45
* https://github.com/pNre/ExSwift/pull/46
* https://github.com/pNre/ExSwift/pull/48

**Comment by michaeleisel** [comment]
What do you mean, is that all? All of the PRs I've sent in I want to merge, so whatever they would be is all.

**Pull request merged**
